### ISSUE TITLE
Client Networking Error 10061

### ISSUE THREAD

**Issue by zatee** [VirtualPuppet/XignCode3-bypass#3]
I'm constantly getting this error as seen in the attached screenshot:

![error](https://user-images.githubusercontent.com/29353168/27011474-1fc28068-4e71-11e7-87b9-79dbbfcee62c.png)

-I do not have Windows Firewall or any kind of AV enabled
-I tried enabling some network services (according to google)

I'm trying to make this bypass work for another game so I changed:
-XIGNCODE license key (XIGNCODE.cpp)
-all references to Maplestory to my game
-I did not touch the ASM code yet

**Comment by VirtualPuppet** [comment]
I haven't worked on this project for almost 2-3 years, so I don't really remember the intrinsics :P

**Comment by zatee** [comment]
I guess I have to change the ASM code

Thanks anyway :)
You can close this issue.
