### ISSUE TITLE
cant compile on Visual Studio 2015

### ISSUE THREAD

**Issue by Krzhub** [VirtualPuppet/XignCode3-bypass#6]
hello Sir,

I can't compile your code using Visual Studio 2015. Building solution Client/Host throws many errors:
![image](https://user-images.githubusercontent.com/34978892/34539230-fa32cde2-f0cf-11e7-84f2-89a53575ba88.png)

could you, please give me a hint how to make it run?

thank you,
Rafał

**Comment by Krzhub** [comment]
Hello again,

I've changed IDE to Lazurus. Solution has been built according to the plan, but it did not met expectations on CE is detected. Game name is CAbal, I run it from steam. What information would you need to help me fix this?

thanks

**Comment by VirtualPuppet** [comment]
The source is from when XignCode 3 was new. It might have become deprecated or patched.
