### ISSUE TITLE
A question about your project

### ISSUE THREAD

**Issue by 1337lol** [VirtualPuppet/XignCode3-bypass#9]
I would like to ask a question about this when i log into the game client and after 3-4 the dll response with this:
Client networking error: Failed to connect to the server.
Reason: Unknown. Error code: 10061.
interaction returned: 0

i set inet_addr to 127.0.0.1
what i am doing wrong can you help me?

Thank you in advance :)

P.S. So i fixed almost everything but the host.exe closes instantly after i open it,i've configured the paths to my game.

**Comment by burakcetin** [comment]
I have the same problem. Anyone found a solution?

**Comment by 1337lol** [comment]
So can anyone help us?

**Comment by saadox** [comment]
You're doing it wrong bud .

**Comment by VirtualPuppet** [comment]
Well, I didn't upload this in order to act as customer support for people who wanted to use it - it was posted for educational purposes only.
